{% set bc = build_clause | default(values.build) %}
{% if bc.prepare and bc.prepare is mapping and current_build_stage == 'prepare' %}
FROM {{ bc.base }} AS prepare
WORKDIR {{ bc.workdir }}
ADD --chown=1001:1001 . {{ bc.workdir }}

{% if bc.prepare.env %}
ENV {% for k, v in bc.prepare.env.items() %}{{ k }}={{ v | to_json }} {% endfor %}
{% endif %}

{% for l in bc.prepare.script %}
RUN {{ l }}
{% endfor %}

RUN find . -type f {% if bc.prepare.keep %}{% for k in bc.prepare.keep %}{% if not loop.first %} -and {% endif %} -not -path '{{ k }}' -and -not -path '{{ k }}/*' {% endfor %}{% endif %} -delete
{% endif %}

{% set release = bc.release | default(values.release | default(None)) %}
{% set release_copy = release['copy'] if release is mapping else release.copy_ %}
{% if from_build_image %}
FROM {{ from_build_image }} AS build
{% elif shared_prepare_repo %}
FROM {{ cluster_config.registry }}/{{ shared_prepare_repo }}:prepare AS build
{% elif bc.prepare and bc.prepare is mapping %}
FROM {{ cluster_config.registry }}/{{ build_image_repo }}:prepare AS build
{% else %}
FROM {{ bc.base }} AS build
{% endif %}
WORKDIR {{ bc.workdir }}
{% if bc.env %}
ENV {% for k, v in bc.env.items() %}{{ k }}={{ v | to_json }} {% endfor %}
{% endif %}

{% if lain_meta %}
ENV LAIN_META={{ lain_meta }}
{% endif %}

ADD --chown=1001:1001 . {{ bc.workdir }}
{% if bc.script %}
RUN ({{ ') && ('.join(bc.script) }})
{% endif %}

{% if release %}
FROM {{ release.dest_base }} AS release
WORKDIR {{ release.workdir }}
{% if lain_meta %}
ENV LAIN_META={{ lain_meta }}
{% endif %}

{% for copy in release_copy %}
COPY --chown=1001:1001 --from=build {{ copy.src }} {{ copy.dest }}
{% endfor %}

{% if release.env %}
ENV {% for k, v in release.env.items() %}{{ k }}={{ v | to_json }} {% endfor %}
{% endif %}

{% if release.script %}
RUN ({{ ') && ('.join(release.script) }})
{% endif %}
{% endif %}

USER 1001
