pypi_index: https://pypi.0xgl.xyz/simple/

registry: 625766999175.dkr.ecr.us-west-2.amazonaws.com
registry_token_fetch_cmd: "aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken'"
registry_token_type: "Basic"
registry_endpoint_use_https: yes

domain: 0xgl.xyz

ingressClass: nginx-internal
externalIngressClass: nginx-external
supportsIngressClassName: true
clusterIssuer: letsencrypt-dns01

prometheus: https://prometheus.0xgl.xyz
pql_template:
  cpu: |
    max(rate(container_cpu_user_seconds_total{{container!="sandbox",pod=~"{appname}-{proc_name}-[[:alnum:]]+-.+"}}[{range}]) * 1000)
  memory_quantile: |
    max(
      quantile_over_time(0.99,
      container_memory_usage_bytes{{container!="sandbox",pod=~"{appname}-{proc_name}-[[:alnum:]]+-.+"}}[{range}]
    ) - quantile_over_time(0.99,
      container_memory_cache{{container!="sandbox",pod=~"{appname}-{proc_name}-[[:alnum:]]+-.+"}}[{range}]
    ))
grafana_url: https://grafana.0xgl.xyz/d/7sl4vJAZk/container-monitoring

extra_docs: >
  GrandLine Production Cluster ，请参考 https://github.com/nftxyz/lain-cli/blob/master/lain_cli/cluster_values/grandline.md 生成配置
