pypi_index: https://pypi.0xgl.xyz

registry: 625766999175.dkr.ecr.us-west-2.amazonaws.com
registry_token_fetch_cmd: "aws ecr get-authorization-token --output text --query 'authorizationData[].authorizationToken'"
registry_token_type: "Basic"
registry_endpoint_use_https: yes

domain: 0xgl.xyz

ingressClass: nginx-internal
externalIngressClass: nginx-external
clusterIssuer: letsencrypt-dns01

extra_docs: >
  GrandLine Production Cluster ，请参考 https://github.com/nftxyz/lain-cli/blob/master/lain_cli/cluster_values/grandline.md 生成配置

clusterPersistentVolumeClaims:
  juicefs:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10Pi
    storageClassName: juicefs-sc
