pypi_index: https://git.ysdev.xyz/api/v4/projects/9/packages/pypi/simple
pypi_extra_index: https://mirrors.cloud.tencent.com/pypi/simple/
registry: ccr.ccs.tencentyun.com/yashi
registry_type: tencent
prometheus: http://prometheus.ysdev.xyz
pql_template:
  cpu: |
    max(rate(container_cpu_user_seconds_total{{container!="sandbox",pod=~"{appname}-{proc_name}-[[:alnum:]]+-.+"}}[{range}]) * 1000)
  memory_quantile: |
    max(
      quantile_over_time(0.99,
      container_memory_usage_bytes{{container!="sandbox",pod=~"{appname}-{proc_name}-[[:alnum:]]+-.+"}}[{range}]
    ) - quantile_over_time(0.99,
      container_memory_cache{{container!="sandbox",pod=~"{appname}-{proc_name}-[[:alnum:]]+-.+"}}[{range}]
    ))
grafana_url: http://grafana.ysdev.xyz/d/7sl4vJAZk/docker-monitoring
kibana: kibana.ysdev.xyz
gitlab: http://git.ysdev.xyz
domain: ysdev.xyz
remote_docker: 10.22.182.12
secrets_env:
  access_key_id:
    env_name: YASHI_TENCENT_SECRET_ID
    hint: 'you can find them in 1pw: [yashi] qcloud registry user'
  access_key_secret:
    env_name: YASHI_TENCENT_SECRET_KEY
    hint: 'you can find them in 1pw: [yashi] qcloud registry user'
extra_docs: |
  雅识生产集群, 请添加 /etc/hosts: 10.22.192.13 cls-18ny69zr.ccs.tencent-cloud.com
clusterHostAliases:
- ip: "10.22.192.13"
  hostnames:
    - "cls-18ny69zr.ccs.tencent-cloud.com"

ingressClass: lain-internal
externalIngressClass: lain-external
clusterIssuer: cert-manager-webhook-dnspod-cluster-issuer

serviceAnnotations:
  service.cloud.tencent.com/direct-access: "true"

ingressAnnotations:
  ingress.cloud.tencent.com/direct-access: "true"

externalIngressAnnotations:
  ingress.cloud.tencent.com/direct-access: "true"
