repos:

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
        exclude: lain_cli/chart_template
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--skip-string-normalization']

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture
        types: [python]
        args:
          - lain_cli

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pytest-style
          - flake8-bugbear
          - flake8-logging-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
        args: ["-ll", "-c", ".bandit.yml"]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint

  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        name: pylint
        types: [python]
        entry: python -m pylint.__main__
        language: system
        args:
          [
            "-rn",
            "-sn",
            "--rcfile=pylintrc",
          ]
