on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credenticals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"
          mask-aws-account-id: "no"

      - name: Login in Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Create repository in ECR if not exists
        uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          repository: "lain"

      - name: Build
        run: >
          docker build .
          -t ${{ steps.ecr.outputs.repository-uri }}
          --build-arg BASE=${{ steps.login-ecr.outputs.registry }}/python:3.10

      - name: Push
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: docker push ${{ steps.ecr.outputs.repository-uri }}
