on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-west-2

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, x64, ubuntu]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login in Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Create repository in ECR if not exists
        uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          repository: "lain"

      - name: Build
        run: >
          docker build .
          -t ${{ steps.ecr.outputs.repository-uri }}
          --build-arg BASE=${{ steps.login-ecr.outputs.registry }}/python:3.10

      - name: Push
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: docker push ${{ steps.ecr.outputs.repository-uri }}
